#write a code to simulate 777 game
import random
hidden=random.randrange(1,8)
hidden1=random.randrange(1,8)
hidden2=random.randrange(1,8)
guess=int(input('please enter your guess between 1 and 7:'))
guess1=int(input('please enter your guess between 1 and 7:'))
guess2=int(input('please enter your guess between 1 and 7:'))
print("number generated by computer is:",hidden,hidden1,hidden2)
if guess==hidden==guess1==guess2==hidden1==hidden2:
    print("hit")
else :
    print('better luck next time')
input()

